# Generated by Django 6.0.5 on 2026-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
            ],
        ),
    ]
