# Generated by Django 6.0.5 on 2026-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('penulis', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/img/')),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('artikel', 'Artikel'), ('berita', 'Berita')], default='artikel', max_length=20)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
