# Generated by Django 6.0.5 on 2026-06-19 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('deskripsi', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/img/home')),
                ('notes', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
