# Generated by Django 6.0.5 on 2026-06-19 13:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='nama',
        ),
        migrations.AlterField(
            model_name='home',
            name='deskripsi',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
