# Generated by Django 6.0.5 on 2026-06-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_title_home_nama_alter_home_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_at']},
        ),
    ]
